version: '3.4'
services:
  mysql:
    image: mysql:5.7
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_DATABASE: nodejs-sam-rdsproxy-sample
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: passw0rd
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
